### ISSUE TITLE
What are the deps?

### ISSUE THREAD

**Issue by latepaul** [actualbudget/actual-server#10]
The README says to "install deps" but doesn't say what they are.

Thanks

**Comment by wmertens** [comment]
run `yarn`

**Comment by latepaul** [comment]
So as I understand it that would install yarn. If I run it it tells me that yarn is already up to date. So I take it it's not referring to further dependencies?

I'm asking because I get this:
```

$ yarnpkg start
yarn run v1.22.10
$ node app
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'fs/promises'
Require stack:
- /home/paul/Projects/actual-server/app-sync.js
- /home/paul/Projects/actual-server/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/paul/Projects/actual-server/app-sync.js:2:10)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/paul/Projects/actual-server/app-sync.js',
    '/home/paul/Projects/actual-server/app.js'
  ]
}
```
I guess I assumed that the missing "fs/promises" module could be part of the dependencies.

**Comment by latepaul** [comment]
OK I've been able to run this up by creating a docker image. I just wanted to try it out to see how it compares to other similar software I've used. 

I don't want to waste anyone's time on pursuing this so I'll close this issue.

Thanks anyway.
