### ISSUE TITLE
[Bug]: CI - out of memory errors

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual-server#287]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

The edge docker build CI jobs sometimes randomly fail. This is especially annoying for the scheduled `edge` releases we have every day. Sometimes consecutive days fail running, so we don't get as frequent releases. I haven't been able to figure out why.. 

Example: https://github.com/actualbudget/actual-server/actions/runs/7066898754/job/19239533606

```
#51 [linux/arm/v7 base  6/12] RUN yarn workspaces focus --all --production
#51 11.21 ➤ YN0000: ┌ Resolution step
#51 12.19 ➤ YN0085: │ - @ampproject/remapping@npm:2.2.0, @babel/code-frame@npm:7.18.6, @babel/code-frame@npm:7.22.13, @babel/compat-data@npm:7.20.14, @babel/core@npm:7.20.12, and 384 more.
#51 12.28 ➤ YN0000: └ Completed in 1s 67ms
#51 12.30 ➤ YN0000: ┌ Fetch step
#51 50.61 ➤ YN0001: │ Error: @actual-app/web@npm:23.11.0: Couldn't allocate enough memory
#51 50.61     at Ji.allocateBuffer (/app/.yarn/releases/yarn-4.0.1.cjs:149:204491)
#51 50.61     at Ji.allocateUnattachedSource (/app/.yarn/releases/yarn-4.0.1.cjs:149:204733)
#51 50.61     at new Ji (/app/.yarn/releases/yarn-4.0.1.cjs:149:193911)
#51 50.61     at Object.sut (/app/.yarn/releases/yarn-4.0.1.cjs:192:212275)
#51 50.61     at async dl.fetchFromNetwork (/app/.yarn/releases/yarn-4.0.1.cjs:678:3118)
#51 50.61     at async v (/app/.yarn/releases/yarn-4.0.1.cjs:199:1576)
#51 50.61     at async x (/app/.yarn/releases/yarn-4.0.1.cjs:199:1916)
#51 50.61     at async E (/app/.yarn/releases/yarn-4.0.1.cjs:199:3257)
#51 50.61     at async Lr.fetchPackageFromCache (/app/.yarn/releases/yarn-4.0.1.cjs:199:3378)
#51 50.61     at async dl.fetch (/app/.yarn/releases/yarn-4.0.1.cjs:678:2469)
#51 ...

#43 [linux/arm/v6 base  6/12] RUN yarn workspaces focus --all --production
#43 70.16 ➤ YN0013: │ 239 packages were added to the project (+ 53.6 MiB).
#43 70.17 ➤ YN0000: └ Completed in 58s 415ms
#43 70.17 ➤ YN0000: ┌ Link step
#43 CANCELED

#51 [linux/arm/v7 base  6/12] RUN yarn workspaces focus --all --production
#51 75.13 ➤ YN0000: └ Completed in 1m 3s
#51 75.14 ➤ YN0000: · Failed with errors in 1m 5s
#51 ERROR: process "/bin/sh -c yarn workspaces focus --all --production" did not complete successfully: exit code: 1

#45 [linux/arm64 base  6/12] RUN yarn workspaces focus --all --production
#45 CANCELED
------
 > [linux/arm/v7 base  6/12] RUN yarn workspaces focus --all --production:
50.61     at new Ji (/app/.yarn/releases/yarn-4.0.1.cjs:149:193911)
50.61     at Object.sut (/app/.yarn/releases/yarn-4.0.1.cjs:192:212275)
50.61     at async dl.fetchFromNetwork (/app/.yarn/releases/yarn-4.0.1.cjs:678:3118)
50.61     at async v (/app/.yarn/releases/yarn-4.0.1.cjs:199:1576)
50.61     at async x (/app/.yarn/releases/yarn-4.0.1.cjs:199:1916)
50.61     at async E (/app/.yarn/releases/yarn-4.0.1.cjs:199:3257)
50.61     at async Lr.fetchPackageFromCache (/app/.yarn/releases/yarn-4.0.1.cjs:199:3378)
50.61     at async dl.fetch (/app/.yarn/releases/yarn-4.0.1.cjs:678:2469)
75.13 ➤ YN0000: └ Completed in 1m 3s
75.14 ➤ YN0000: · Failed with errors in 1m 5s
------
edge-alpine.Dockerfile:6
--------------------
   4 |     ADD .yarn ./.yarn
   5 |     ADD yarn.lock package.json .yarnrc.yml ./
   6 | >>> RUN yarn workspaces focus --all --production
   7 |     RUN if [ "$(uname -m)" = "armv7l" ]; then npm install bcrypt better-sqlite3 --build-from-source; fi
   8 |     
```

### Where are you hosting Actual?

None

### Operating System

None

**Comment by twk3** [comment]
Setting the max-parallelism to 2 might help. Particularly on the alpine jobs, which are trying to run 4 docker builds at the same time on the same resource. https://docs.docker.com/build/ci/github-actions/configure-builder/#max-parallelism

This will double the runtime of those jobs though. Potentially more than double if the v6 build is the one starting last as it's also the slowest.

**Comment by twk3** [comment]
I tested max-parallelism, but it didn't seem to help. Might be more related to an issue yarn seems to have with 32bit fetches.

limiting yarn concurrency, at least on 32bit, might help. Might be related to https://github.com/yarnpkg/berry/issues/3972
