### ISSUE TITLE
[Bug]: Installation Error yarn

### ISSUE THREAD

**Issue by Marcx87** [actualbudget/actual-server#426]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Received an error trying to install actual-server using yarn.

### What error did you receive?

[root@]# git clone https://github.com/actualbudget/actual-server.git
Cloning into 'actual-server'...
remote: Enumerating objects: 2065, done.
remote: Counting objects: 100% (558/558), done.
remote: Compressing objects: 100% (186/186), done.
remote: Total 2065 (delta 463), reused 398 (delta 368), pack-reused 1507 (from 1)
Receiving objects: 100% (2065/2065), 4.52 MiB | 6.11 MiB/s, done.
Resolving deltas: 100% (1180/1180), done.
[root@]# cd actual-server
[root@actual-server]# yarn install
/opt/actual-server/.yarn/releases/yarn-4.3.1.cjs:4
(()=>{var $3e=Object.create;var NF=Object.defineProperty;var e_e=Object.getOwnPropertyDescriptor;var t_e=Object.getOwnPropertyNames;var r_e=Object.getPrototypeOf,n_e=Object.prototype.hasOwnProperty;var ve=(t=>typeof require<"u"?require:typeof Proxy<"u"?new Proxy(t,{get:(e,r)=>(typeof require<"u"?require:e)[r]}):t)(function(t){if(typeof require<"u")return require.apply(this,arguments);throw new Error('Dynamic require of "'+t+'" is not supported')});var Et=(t,e)=>()=>(t&&(e=t(t=0)),e);var _=(t,e)=>()=>(e||t((e={exports:{}}).exports,e),e.exports),zt=(t,e)=>{for(var r in e)NF(t,r,{get:e[r],enumerable:!0})},i_e=(t,e,r,o)=>{if(e&&typeof e=="object"||typeof e=="function")for(let a of t_e(e))!n_e.call(t,a)&&a!==r&&NF(t,a,{get:()=>e[a],enumerable:!(o=e_e(e,a))||o.enumerable});return t};var Ze=(t,e,r)=>(r=t!=null?$3e(r_e(t)):{},i_e(e||!t||!t.__esModule?NF(r,"default",{value:t,enumerable:!0}):r,t));var vi={};zt(vi,{SAFE_TIME:()=>x7,S_IFDIR:()=>IP,S_IFLNK:()=>BP,S_IFMT

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

### Where are you hosting Actual?

Locally via Yarn

### Operating System

Linux

**Comment by Marcx87** [comment]
sorry!!! old version of npm
