### ISSUE TITLE
[Bug]: Some peer dependencies are incorrectly met by your project

### ISSUE THREAD

**Issue by mbrijun** [actualbudget/actual-server#477]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

During "yarn install", the following error message is presented. This however does not seem to affect the functionality.

```
YN0002: actual-sync@workspace:. doesn't provide @babel/core (p89c81), requested by @babel/preset-typescript.
YN0086: Some peer dependencies are incorrectly met by your project; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
```

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Firefox

### Operating System

Windows 11

**Comment by JesusRevelles** [comment]
Im getting the same, and also a better-sqlite3 issue, it may be related:
 
`YN0007: │ better-sqlite3@npm:11.5.0 must be built because it never has been before or the last one failed`

Which then prevents yarn start to run:
`TypeError: Cannot open database because the directory does not exist
    at new Database (/Users/sheevalum/Applications/actual-server/node_modules/better-sqlite3/lib/database.js:65:9)
    at openDatabase (file:///Users/sheevalum/Applications/actual-server/src/db.js:57:30)
    at getAccountDb (file:///Users/sheevalum/Applications/actual-server/src/account-db.js:12:18)
    at file:///Users/sheevalum/Applications/actual-server/src/app-sync/services/files-service.js:195:39
    at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)`

**Comment by mbrijun** [comment]
@JesusRevelles - in my case, everything starts OK. I think I also saw the sqlite warning the first time I ran yarn, but it likely is just for your informatoin (i.e., not an error). I was using the default configuration on Windows 11, where I did "git clone" first, followed by "yarn install" and then "yarn start". I can see 2 files with .sqlite extension - one in the "server-files" subdirectory, and another one in the "user-files" subdirectory.

**Comment by JesusRevelles** [comment]
I'm getting the same issue, which then it's preventing the app to run with this error:

`TypeError: Cannot open database because the directory does not exist
    at new Database (/Users/sheevalum/Applications/actual-server/node_modules/better-sqlite3/lib/database.js:65:9)
    at openDatabase (file:///Users/sheevalum/Applications/actual-server/src/db.js:57:30)
    at getAccountDb (file:///Users/sheevalum/Applications/actual-server/src/account-db.js:12:18)
    at file:///Users/sheevalum/Applications/actual-server/src/app-sync/services/files-service.js:195:39
    at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)`

**Comment by mbrijun** [comment]
@JesusRevelles - could it be an issue that data directories do not exist? You can try pre-creating them and running "yarn start" again.

**Comment by JesusRevelles** [comment]
@mbrijun indeed, that solved the issue. Thanks mate.

After debugging it, it seems the code is looking for three files that are not coming by standard in the repo and they should:

- server-files folder
- user-files folder
- .migrate

**Comment by maciejmatczak** [comment]
I've also seen similar issue for `proxy-addr`:

```
Error: Your application tried to access proxy-addr, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

Required package: proxy-addr (via "proxy-addr/package.json")
Required by: /opt/actualbudget/src/util/validate-user.js
```
