### ISSUE TITLE
Unable to do anything after update.

### ISSUE THREAD

**Issue by Landelor** [actualbudget/actual-server#48]
Running Actual-Server in docker.
After updating nothing is working. Server showing offline. File won't load.
Getting this error in the logs:

`Rejection: TypeError: res.status is not a function
    at middleware (/app/util/error-middleware.js:3:7)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/app/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
    at /app/node_modules/express/lib/router/index.js:284:7`

**Comment by Landelor** [comment]
Running from InPrivate getting this:
<img width="268" alt="image" src="https://user-images.githubusercontent.com/8555004/170603486-47895dd1-f9ed-41ad-b2cf-ed3a6007466c.png">

**Comment by kurtaschliman** [comment]
See #40. Fix in the PR #46 seems to be working for me now.

**Comment by Landelor** [comment]
That did the trick.
I'll close this one seeing as it's a duplicate.
