### ISSUE TITLE
Error: "budget directory does not exist" when using specifying ACTUAL_USER_FILES

### ISSUE THREAD

**Issue by breucode** [actualbudget/actual-server#58]
I set ACTUAL_USER_FILES to "/data" (mentioned in the README), to be able to backup my actual-server data.

When using this setting, syncing does not work any more and I can't close the budget in the Frontend.

I used the latest docker image to run the actual-server.

The error message in the server is:

```
[Exception] Error: budget directory does not exist
    at loadBudget (/app/node_modules/@actual-app/api/app/bundle.api.js:57516:83)
    at async module.exports../packages/loot-core/src/server/main.js.handlers.load-budget (/app/node_modules/@actual-app/api/app/bundle.api.js:57251:13)
error SELECT timestamp, dataset, row, column, value FROM messages_crdt WHERE timestamp > ?
Rejection: TypeError: Cannot read properties of undefined (reading 'prepare')
    at Module.runQuery (/app/node_modules/@actual-app/api/app/bundle.api.js:45806:41)
    at Module.runQuery (/app/node_modules/@actual-app/api/app/bundle.api.js:54349:82)
    at getMessagesSince (/app/node_modules/@actual-app/api/app/bundle.api.js:61540:54)
    at Object.syncAndReceiveMessages (/app/node_modules/@actual-app/api/app/bundle.api.js:61543:29)
    at syncAPI (/app/sync-full.js:30:45)
```

**Comment by breucode** [comment]
Workaround for me: Do not specify `ACTUAL_USER_FILES`. When creating a volume with `docker run -p 5006:5006 -v actual_data:/data jlongster/actual-server`, the server and user files are in the /data directory.

**Comment by j-f1** [comment]
I’m closing this for now, I think the underlying issue may be that the server will pick up `/data/server-files` as the folder for server files if `/data` is available. We have more thorough docs for configuration now so hopefully folks won’t accidentally do that now.
