### ISSUE TITLE
Error on fresh install: Server does not look like an Actual server. Is it set up correctly?

### ISSUE THREAD

**Issue by auspiciousdiviner** [actualbudget/actual-server#84]
Apologies if I'm missing something obvious, I wanted to try to get this to work so that I can access my file from each device on my network.

I followed the quick guide to get it up and running inside of a linux container. but it seems that for some odd reason it can't find itself. Following the instructions in "Configuring the server URL" leads to a confusing error message in the client: `Server does not look like an Actual server. Is it set up correctly?`

The container sits behind an nginx reverse proxy and is accessible from a custom domain name within my personal network, the names resolve just fine both inside and outside the container. But I've also tried using the actual IP of the reverse proxy and even the IP of the container itself, to no avail. Even in connecting directly to the container's IP and putting that IP into the input.

The nodejs app also spits out this error in stdout: 
```
Oct 18 10:34:55 actual yarn[878]: ERROR Error: Could not locate the bindings file. Tried:
Oct 18 10:34:55 actual yarn[878]:  → /root/actual-server/node_modules/better-sqlite3/build/better_sqlite3.node
Oct 18 10:34:55 actual yarn[878]:  → /root/actual-server/node_modules/better-sqlite3/build/Debug/better_sqlite3.node
Oct 18 10:34:55 actual yarn[878]:  → /root/actual-server/node_modules/better-sqlite3/build/Release/better_sqlite3.node
Oct 18 10:34:55 actual yarn[878]:  → /root/actual-server/node_modules/better-sqlite3/out/Debug/better_sqlite3.node
Oct 18 10:34:55 actual yarn[878]:  → /root/actual-server/node_modules/better-sqlite3/Debug/better_sqlite3.node
Oct 18 10:34:55 actual yarn[878]:  → /root/actual-server/node_modules/better-sqlite3/out/Release/better_sqlite3.node
Oct 18 10:34:55 actual yarn[878]:  → /root/actual-server/node_modules/better-sqlite3/Release/better_sqlite3.node
Oct 18 10:34:55 actual yarn[878]:  → /root/actual-server/node_modules/better-sqlite3/build/default/better_sqlite3.node
Oct 18 10:34:55 actual yarn[878]:  → /root/actual-server/node_modules/better-sqlite3/compiled/18.11.0/linux/x64/better_sqlite3.node
Oct 18 10:34:55 actual yarn[878]:  → /root/actual-server/node_modules/better-sqlite3/addon-build/release/install-root/better_sqlite3.node
Oct 18 10:34:55 actual yarn[878]:  → /root/actual-server/node_modules/better-sqlite3/addon-build/debug/install-root/better_sqlite3.node
Oct 18 10:34:55 actual yarn[878]:  → /root/actual-server/node_modules/better-sqlite3/addon-build/default/install-root/better_sqlite3.node
Oct 18 10:34:55 actual yarn[878]:  → /root/actual-server/node_modules/better-sqlite3/lib/binding/node-v108-linux-x64/better_sqlite3.node
Oct 18 10:34:55 actual yarn[878]:     at bindings (/root/actual-server/node_modules/bindings/bindings.js:126:9)
Oct 18 10:34:55 actual yarn[878]:     at new Database (/root/actual-server/node_modules/better-sqlite3/lib/database.js:48:64)
Oct 18 10:34:55 actual yarn[878]:     at openDatabase (/root/actual-server/db.js:38:30)
Oct 18 10:34:55 actual yarn[878]:     at getAccountDb (/root/actual-server/account-db.js:17:17)
Oct 18 10:34:55 actual yarn[878]:     at /root/actual-server/app-account.js:25:19
Oct 18 10:34:55 actual yarn[878]:     at Layer.handle [as handle_request] (/root/actual-server/node_modules/express/lib/router/layer.js:95:5)
Oct 18 10:34:55 actual yarn[878]:     at next (/root/actual-server/node_modules/express/lib/router/route.js:137:13)
Oct 18 10:34:55 actual yarn[878]:     at Route.dispatch (/root/actual-server/node_modules/express/lib/router/route.js:112:3)
Oct 18 10:34:55 actual yarn[878]:     at Layer.handle [as handle_request] (/root/actual-server/node_modules/express/lib/router/layer.js:95:5)
Oct 18 10:34:55 actual yarn[878]:     at /root/actual-server/node_modules/express/lib/router/index.js:281:22 {
Oct 18 10:34:55 actual yarn[878]:   tries: [
Oct 18 10:34:55 actual yarn[878]:     '/root/actual-server/node_modules/better-sqlite3/build/better_sqlite3.node',
Oct 18 10:34:55 actual yarn[878]:     '/root/actual-server/node_modules/better-sqlite3/build/Debug/better_sqlite3.node',
Oct 18 10:34:55 actual yarn[878]:     '/root/actual-server/node_modules/better-sqlite3/build/Release/better_sqlite3.node',
Oct 18 10:34:55 actual yarn[878]:     '/root/actual-server/node_modules/better-sqlite3/out/Debug/better_sqlite3.node',
Oct 18 10:34:55 actual yarn[878]:     '/root/actual-server/node_modules/better-sqlite3/Debug/better_sqlite3.node',
Oct 18 10:34:55 actual yarn[878]:     '/root/actual-server/node_modules/better-sqlite3/out/Release/better_sqlite3.node',
Oct 18 10:34:55 actual yarn[878]:     '/root/actual-server/node_modules/better-sqlite3/Release/better_sqlite3.node',
Oct 18 10:34:55 actual yarn[878]:     '/root/actual-server/node_modules/better-sqlite3/build/default/better_sqlite3.node',
Oct 18 10:34:55 actual yarn[878]:     '/root/actual-server/node_modules/better-sqlite3/compiled/18.11.0/linux/x64/better_sqlite3.node',
Oct 18 10:34:55 actual yarn[878]:     '/root/actual-server/node_modules/better-sqlite3/addon-build/release/install-root/better_sqlite3.node',
Oct 18 10:34:55 actual yarn[878]:     '/root/actual-server/node_modules/better-sqlite3/addon-build/debug/install-root/better_sqlite3.node',
Oct 18 10:34:55 actual yarn[878]:     '/root/actual-server/node_modules/better-sqlite3/addon-build/default/install-root/better_sqlite3.node',
Oct 18 10:34:55 actual yarn[878]:     '/root/actual-server/node_modules/better-sqlite3/lib/binding/node-v108-linux-x64/better_sqlite3.node'
Oct 18 10:34:55 actual yarn[878]:   ]
Oct 18 10:34:55 actual yarn[878]: }
```

My knowledge of nodejs is zero but I'm assuming this is the actual reason behind why I'm unable to connect? Any ideas of what I can do to fix this? Thanks.

**Comment by rich-howell** [comment]
Hey @auspiciousdiviner,

I don't suppose you would mind opening this issue over in [Actual/Docs](https://github.com/actualbudget/docs) would you? I want to give you the credit for this but think it would a great article for the documentation and I can't transfer it from Actual/Actual-server into Docs.

Cheers
Rich

**Comment by auspiciousdiviner** [comment]
Uh, sure, do you want me to just blindly copy and paste what I have posted here to over there?

**Comment by rich-howell** [comment]
> Uh, sure, do you want me to just blindly copy and paste what I have posted here to over there?

Yes please
